# Generated by Django 4.2 on 2024-09-01 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'db_table': 'email',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'db_table': 'keyword',
            },
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('relevant', models.BooleanField(default=False)),
                ('source', models.BooleanField(default=False)),
                ('forum', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Param',
                'verbose_name_plural': 'Params',
                'db_table': 'param',
            },
        ),
        migrations.CreateModel(
            name='ParamKeyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_param.keyword')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_param.param')),
            ],
            options={
                'verbose_name': 'Param Keyword',
                'verbose_name_plural': 'Params Keywords',
                'db_table': 'param_keyword',
            },
        ),
        migrations.CreateModel(
            name='ParamEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_param.email')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_param.param')),
            ],
            options={
                'verbose_name': 'Param Email',
                'verbose_name_plural': 'Params Emails',
                'db_table': 'param_email',
            },
        ),
    ]
