# Generated by Django 4.2 on 2024-09-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_param', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='param',
            name='emails',
            field=models.ManyToManyField(through='api_param.ParamEmail', to='api_param.email'),
        ),
        migrations.AddField(
            model_name='param',
            name='keywords',
            field=models.ManyToManyField(through='api_param.ParamKeyword', to='api_param.keyword'),
        ),
    ]
