services:
  db:
    image: postgres:16
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ${PGDATA_PATH}:/var/lib/postgresql/data

  api:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: cti_alerts_api
    command: gunicorn -w 4 --threads 2 cti.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./api:/api
      - static_volume:/api/staticfiles/
      - media_volume:/api/mediafiles/
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: cti_alerts_nginx
    volumes:
      - static_volume:/api/staticfiles/
      - media_volume:/api/mediafiles/
    ports:
      - "443:443"
    depends_on:
      - api

volumes:
  static_volume:
  media_volume:
