# Generated by Django 4.2 on 2024-09-03 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_param', '0002_param_emails_param_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'db_table': 'source',
            },
        ),
        migrations.RenameField(
            model_name='param',
            old_name='forum',
            new_name='search_keyword',
        ),
        migrations.RenameField(
            model_name='param',
            old_name='relevant',
            new_name='search_source',
        ),
        migrations.RemoveField(
            model_name='param',
            name='source',
        ),
        migrations.AddField(
            model_name='param',
            name='is_relevant',
            field=models.FloatField(default=1.0),
        ),
        migrations.CreateModel(
            name='ParamSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_param.param')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_param.source')),
            ],
            options={
                'verbose_name': 'Param Source',
                'verbose_name_plural': 'Params Sources',
                'db_table': 'param_source',
            },
        ),
        migrations.AddField(
            model_name='param',
            name='sources',
            field=models.ManyToManyField(through='api_param.ParamSource', to='api_param.source'),
        ),
    ]
