# Generated by Django 4.2 on 2024-10-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_param', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='last_run',
            field=models.DateField(blank=True, null=True),
        ),
    ]
