# Generated by Django 4.2 on 2025-02-09 23:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id_user', models.IntegerField()),
                ('start_date', models.DateField()),
                ('final_date', models.DateField()),
                ('qte_frequency', models.IntegerField()),
                ('type_frequency', models.CharField(max_length=100)),
                ('is_relevant', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('last_run', models.DateField()),
                ('run', models.DateField()),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alert_param"."alert',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'db_table': 'alert_param"."email',
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forum_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Forum',
                'verbose_name_plural': 'Forums',
                'db_table': 'alert_param"."forum',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'db_table': 'alert_param"."keyword',
            },
        ),
        migrations.CreateModel(
            name='PostAlerted',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_post', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('relevance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('date', models.DateField()),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert_param.alert')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert_param.forum')),
                ('keywords_found', models.ManyToManyField(to='alert_param.keyword')),
            ],
            options={
                'verbose_name': 'Post Alerted',
                'verbose_name_plural': 'Posts Alerted',
                'db_table': 'alert_param"."post_alerted',
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='emails',
            field=models.ManyToManyField(to='alert_param.email'),
        ),
        migrations.AddField(
            model_name='alert',
            name='forums',
            field=models.ManyToManyField(to='alert_param.forum'),
        ),
        migrations.AddField(
            model_name='alert',
            name='keywords',
            field=models.ManyToManyField(to='alert_param.keyword'),
        ),
    ]
