# Generated by Django 4.2 on 2025-02-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_param', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='name',
            field=models.CharField(default='default_name', max_length=255),
            preserve_default=False,
        ),
    ]
