# Generated by Django 4.2 on 2025-02-07 20:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert_param', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAlerted',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_post', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('relevance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('date', models.DateField()),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert_param.alert')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert_param.forum')),
                ('keywords_found', models.ManyToManyField(to='alert_param.keyword')),
            ],
            options={
                'verbose_name': 'Post Alerted',
                'verbose_name_plural': 'Posts Alerted',
                'db_table': 'alert_param"."generated_alert',
            },
        ),
    ]
